### ISSUE TITLE
Opening esky isnt working in the SOUTH direction.

### ISSUE THREAD

**Issue by TeKGameR950** [MrCrayfish/MrCrayfishFurnitureMod#228] opened 2018-05-28 02:54 UTC
Hi cray, we can't open the esky block when you place it in the SOUTH direction.
As you can see on this GIF
I'm using latest forge and latest version of the furniture mod.

https://imgur.com/a/g0t49cb

Thanks.
Have a good day.

**Comment by MrCrayfish** [comment] 2018-08-09 05:48
Seems to be working in the latest version. Is it in spawn chunks?
Marking this as fixed for now as I can't reproduce in the latest version.

**Closed by MrCrayfish** 2018-08-09 05:48 UTC
