### ISSUE TITLE
curtains in recent version has no color

### ISSUE THREAD

**Issue by Bruno2592** [MrCrayfish/MrCrayfishFurnitureMod#453] opened 2019-09-01 18:08 UTC
the curtains of all colors (yellow, blue, red) when broken, turn white, and when you leave a world or server with some curtain color and return, they turn white (bug in version 1.12.2)

**Comment by Kexerval** [comment] 2019-09-04 20:51
Duplicate of #449

**Closed** 2021-06-09 17:05 UTC
