### ISSUE TITLE
1.12.2-6.3.1 toilet crash

### ISSUE THREAD

**Issue by kreezxil** [MrCrayfish/MrCrayfishFurnitureMod#476] opened 2019-10-10 15:56 UTC
## Steps to reproduce the behavior:

1. craft toilet
1. sit on it

## Minecraft: 
1.12.2
## Forge: 
14.23.5.2847
## Mod Name: 
MrCrayfish's Furniture Mod
## Mod Version: 
6.3.1-1.12.2

## Crash Report: 
https://pastebin.com/p2mKuB89

## Latest Log: 
https://pastebin.com/dXUhPiXT

**Comment by LorenzoPapi** [comment] 2019-10-12 11:40
It's a keybinding problem. When you click on the toilet, it shows the message:
"Press (key) to Fart".
The problem is that the key you set to fart, doesn't have a name to show, so the game crashes.
Or at least, that's what I understood. What key did you set for the fart?

**Comment by kreezxil** [comment] 2019-10-12 23:45
I don't know what the player who reported it to me did to do that. However,
a keybind issue shouldn't cause a crash.

**Comment by LorenzoPapi** [comment] 2019-10-13 07:41
The problem isn't the keybind itself. The problem is the value assigned to the key.
Since this value is negative, usually an impossible thing, Java can't handle it, so it crashes.
Now I'm gonna test the pack to see the error myself

**Comment by kreezxil** [comment] 2019-10-13 13:00
Is MrCrayfish no longer working on his own mods?

**Comment by LorenzoPapi** [comment] 2019-10-13 14:06
It's different. For now, he is ONLY working on the 1.14.4 version of this mod.  And on other small mods like Controllable and Filters.

**Comment by LorenzoPapi** [comment] 2019-10-14 05:35
Sadly, my graphic card isn't good enough to support the pack. So I can't see the problem. If you want, you can ask the player which told you about this problem to record a video in which he shows the key he used and what happens exactly when he sits on the toilet.

**Comment by kreezxil** [comment] 2019-10-14 14:13
I'll see what I can do about after the first two days of Sukkot are over,
ie Tuesday night. I'm fairly certain he's using the default key I'll check
anyways tho.

**Comment by jam325** [comment] 2019-10-14 14:39
Hello, i am not really sure what the key was, and because my pc is in boxes i can't look at the moment. If i am next time at my pc i'll look at it, but i am really sure i have deleted the key because i didn't wanted to sit on a toilet to go around more crashes, if i can help somehow other pls tell me.

**Comment by LorenzoPapi** [comment] 2019-10-17 05:15
Hello, jam325, could you tell us if you tried just once to sit on the toilet, or if you tried to sit a second time or even a third?
Also, were you on the server or in a single player world? Have you tried going in a server or vice versa?

**Comment by jam325** [comment] 2019-10-17 12:23
I tried to sit on the toilet multiple times, like 3 or 4 times, with the keybind set to "none" i can normally sit on it

I was on the world of dragons server from kreezxil

**Comment by LorenzoPapi** [comment] 2019-10-17 12:35
Ok thank you. I knew you could sit with the none key, but we have to know if you changed the key or if it was some kind of compatibility problem

**Comment by kreezxil** [comment] 2019-11-11 15:14
@LorenzoMontanoPecoraro are you able to fix this?

**Comment by LorenzoPapi** [comment] 2019-11-11 15:44
Sadly, I can't reproduce the issue, so there isn't much I can do. We should wait for MrCrayfish to see the issue.

**Comment by kreezxil** [comment] 2019-11-12 16:08
so sad, now i have to block the toilet from being crafted.

**Comment by LorenzoPapi** [comment] 2019-11-12 16:09
That's really bad. In my opinion the toilet is one of the funniest and the most no-sense block in this mod. It's really bad that someone can't use it

**Comment by kreezxil** [comment] 2019-11-13 20:41
you know what the problem is, can't you just code it to not allow a bad
keybind?

**Comment by LorenzoPapi** [comment] 2019-11-13 20:53
You see, it's not that easy. Because for DEFAULT it shouldn't allow a negative value( in this case -96). And then, I'm not some super duper java developer, I'm a person that is slowly learning java trough Minecraft modding. So there isn't anything else I can do. And I'm really sorry to not being able to help. I may try something if I'd know the keybind @jam325 used when his game crashed.

**Comment by jam325** [comment] 2019-11-13 20:55
I think it was "F"

**Comment by LorenzoPapi** [comment] 2019-11-13 20:59
Mmh, there is still an issue. I can't reproduce the crash. So, if you can reproduce the crash, record a video of the crash happening, post it here, along with screens of ALL of your keybinds, I may do something about it

**Comment by jam325** [comment] 2019-11-13 21:00
Ok, but i can't reproduce it now, if my dad see's that my pc is on, is it dead

**Comment by LorenzoPapi** [comment] 2019-11-13 21:03
Well, I have to sleep, since I've got school tomorrow. Goodbye

**Comment by LorenzoPapi** [comment] 2019-12-16 21:02
OKAY GUYS, I'VE GOT NEWS.
So I wasn't totally right about what I previously said....
I forgot how Java worked for a while. So I'm going to explain for everyone: 
the value of the keybinding CAN 
BE NEGATIVE, and these are usually used for mouse buttons;
if you go to https://minecraft.gamepedia.com/Key_codes under the "Mouse" section, you can see that the "-96" code HAS a name, but not a description.
So, the crash MAY occure because of this.

**Comment by LorenzoPapi** [comment] 2019-12-16 21:02
@kreezkil

**Closed as completed** 2021-06-09 17:05 UTC
