### ISSUE TITLE
Crash from Mirror Initialization

### ISSUE THREAD

**Issue by alexgurrola** [MrCrayfish/MrCrayfishFurnitureMod#315] opened 2018-09-16 02:30 UTC
**Describe the bug**
There is an issue when initializing the Mirrors in this mod.  Even if the config has `mirror-enabled=false`, it crashes just the same.  The mod still seems to work fine in an older iteration of my modpack, which was using Forge 1.12.2-14.23.2.2611.  Something may have changed in that time period to cause this issue.

**Crash report**
```
java.lang.NoClassDefFoundError: Could not initialize class com.mrcrayfish.furniture.render.tileentity.MirrorRenderer
```
More information at: https://pastebin.com/VteitpHK

**To Reproduce**
Start Minecraft and watch it die.

Please complete the following information:
- Minecraft Version: Forge 1.12.2-14.23.4.2755
- Mod Versions: 4.1.5-5.10.0

**Comment by fandomaniac** [comment] 2018-09-22 05:49
Is this crash bug still present in version 5.11.0? I'm just asking before I update from 5.9.1 on my SMP server.

**Comment by fandomaniac** [comment] 2018-09-22 06:03
I just tested and the crash bug does still exist in Mod Versions: 5.11.0.

**Comment by alexgurrola** [comment] 2018-09-22 07:45
It may have to do with the Forge Version.

**Comment by fandomaniac** [comment] 2018-09-24 16:53
I'm running Forge 1.12.2-14.23.4.2759. Mirrors are fine on Furniture 5.9.1, with that Forge version, The crash bug started with 5.10.0. I restored my server from backup with the mod rolled-back to 5.9.1. Hopefully this gets fixed on the next update.

**Comment by fandomaniac** [comment] 2018-10-01 18:51
Various Oddities appears to be the cause of this issue. 
From MrCrayfish:
"This is a problem with varodd and their util assuming the view entity is always a player when it can be any entity. I suggest contacting them to add in a check on their side."

I have contacted the developer of Various Oddities to let him know about the issue.

**Comment by fandomaniac** [comment] 2018-10-01 21:59
The developer of Various Oddities responded to my error report:
"I'd argue Crayfish is in error here since it's his code changing the view entity and not mine, but regardless that's a bug I was just about to cause myself so it certainly shouldn't occur in the next beta version."

It sounds like the next Beta version of Various Oddities should correct the compatibility issue with Cray's furniture.

**Comment by alexgurrola** [comment] 2018-10-15 02:44
@fandomaniac I don't use Various Oddities and the issue still exists.

**Comment by MrCrayfish** [comment] 2018-10-15 03:38
@fandomaniac In response to Var Odds, the view entity is of type Entity, not EntityPlayer so it's not safe to cast without checking.

**Closed** 2018-10-15 03:41 UTC

**Comment by MrCrayfish** [comment] 2018-10-19 04:28
@alexgurrola I've not released the update. It's been fixed though in the referenced commit

**Comment by WGandalf7** [comment] 2020-07-27 08:48
Unfortunately, the problem still exists.

**Comment by resetium** [comment] 2021-01-11 16:49
Can confirm, this needs to be reopened

**Comment by mambucodev** [comment] 2023-08-12 19:11
till today, this issue still exists.
