### ISSUE TITLE
[1.15.2] Blinds can see through the world

### ISSUE THREAD

**Issue by ocram9** [MrCrayfish/MrCrayfishFurnitureMod#546] opened 2020-03-17 22:41 UTC
**Versions**
- Minecraft Version: 1.15.2
- Forge Version: 31.1.25
- Mod Version: v7.0.0-pre16

**Describe the bug**
When putting blinds next to a slab or a stair you can see through the world.

**To Reproduce**
The steps to reproduce the behavior:
1. Place blinds next to slabs/stairs // EDIT: this also happens with trapdoors
2. Look through blinds

**Screenshots**
What it looks like through the blinds:
![Screenshot_1](https://user-images.githubusercontent.com/49008532/76908391-d5dc4b00-68a8-11ea-891b-ce0ef4804bb3.png)

What it looks like on the other side:
![Screenshot_2](https://user-images.githubusercontent.com/49008532/76908399-d96fd200-68a8-11ea-828a-d7c6a51aa727.png)

**Comment by MrCrayfish** [comment] 2021-06-09 19:01
Duplicate of https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/447

**Closed as completed by MrCrayfish** 2021-06-09 19:01 UTC
