### ISSUE TITLE
[1.16.4] Blinds remove the colour of glass behind them

### ISSUE THREAD

**Issue by SheltieChan** [MrCrayfish/MrCrayfishFurnitureMod#654] opened 2021-01-25 03:17 UTC
**Describe the bug**
When placing Blinds on coloured glass they cause the glass behind it to be completely invisible instead of maintaining the colour of glass I placed them on.

**Screenshots**
https://imgur.com/a/W7uy4bn

Please complete the following information:
- Minecraft Version: 1.16.4
- Mod Version: v7.0.0-pre19

**Comment by MrCrayfish** [comment] 2021-06-09 21:42
Duplicate of https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/447

**Closed as completed by MrCrayfish** 2021-06-09 21:42 UTC
