### ISSUE TITLE
curtains color

### ISSUE THREAD

**Issue by noy98** [MrCrayfish/MrCrayfishFurnitureMod#432] opened 2019-07-26 13:58 UTC
**Describe the bug**
I just placed any color curtains, it turns to white color.

**Crash report**
If applicable, put a link here to your crash report. MrCrayfish suggests you upload your report to https://pastebin.com/ and then put the link to the paste here.

**To Reproduce**
If applicable, the steps to reproduce the behavior:

**Screenshots**

Please complete the following information:
- Minecraft Version: 1.12.2
- Mod Version: 6.3.0

**Comment by Kexerval** [comment] 2019-09-04 20:52
Duplicate of #449 and #453

**Closed** 2021-06-09 17:04 UTC
