### ISSUE TITLE
Entering water stream from shower crashes server

### ISSUE THREAD

**Issue by bentterp** [MrCrayfish/MrCrayfishFurnitureMod#142] opened 2017-02-03 04:25 UTC
Hi.

My server crashes when I enter the shower after turning on the water:

Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at com.mrcrayfish.furniture.tileentity.TileEntityShowerHead.func_73660_a(TileEntityShowerHead.java:64)
        at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:212)
        at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2745)
        at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjm000(WorldServer.java:2732)
        at net.minecraft.world.World.func_72939_s(World.java:5768)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2122)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Unknown Source)

Full crashlog at https://zerobin.net/?8187af8ecc97f3ab#0XNmH46mwTvtLDydVEStKw49zIn+awi+iKxF1ZWcug4=

cfm-4.1.2-mc1.10.2.jar
forge-1.10.2-12.18.3.2221-universal.jar

**Comment by bentterp** [comment] 2017-02-03 04:26
When I restart the server, the showerhead has disappeared

**Comment by DumF0rGaming** [comment] 2017-02-04 10:59
Confirmed, but my friend had to remove the showerhead manually so I could login

**Comment by njmike** [comment] 2017-02-12 19:00
Seeing the same thing - mount a shower head anywhere, turn it on, walk under it and server crashes.  Can start server again, but server crashes as soon as player logs on in that spot.

Running on CentOS Linux release 7.3.1611 (Core).

Had no trouble with server until this point.  Was also running with JourneyMap and Stellar mods installed, but problem continues to happen after removal of all other mods.



[crash-2017-02-12_13.48.13-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/769538/crash-2017-02-12_13.48.13-server.txt)

**Comment by iBELLinc** [comment] 2017-03-22 03:38
This occurred on our server as well. Another player was locked out of the server because he stood under the shower head and turned it on. Every time he tried to login the server crashed. I was able to successfully travel to his home and enter the room where the shower was running. After right clicking the shower head to turn it off he was able to log in again. The shower head has been removed and blacklisted as an item on our server for the time being. 

cfm-4.1.2-mc1.10.2.jar
forge-1.10.2-12.18.3.2254-universal.jar


[crash-2017-03-20_14.20.38-server.txt](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/files/860281/crash-2017-03-20_14.20.38-server.txt)

**Comment by mmichaelis** [comment] 2017-03-25 18:11
We observed the same issue.

**Workaround:**

Adjust `playerdata/*.dat` file position with [NBTExplorer](https://github.com/jaquadro/NBTExplorer) (used wine on Linux).

**Possible Fix:**

I think this is the same issue as described here:

* shadowfacts/UnderwaterUtilities#7
* shadowfacts/UnderwaterUtilities#11

which is fixed here:

* [shadowfacts/UnderwaterUtilities/commit/3122b187a4](https://github.com/shadowfacts/UnderwaterUtilities/commit/3122b187a4a514e8cd0d64c76f7c3ab64e49f582)

Thus the problem is (referring to the commit) that client side API is used on a server.

**Comment by Phixaen** [comment] 2017-04-17 05:32
Having the same issue here, can get around it by getting rid of the shower but wouldn't mind having it working!

**Comment by piks** [comment] 2017-06-01 19:55
Can confirm, 4.1.2 has this as well, just crashed my minecraft 1.11.2 Ubuntu Server

**Comment by MrCrayfish** [comment] 2017-06-25 03:34
Will look into the issue. Thanks for reporting

**Comment by MrCrayfish** [comment] 2017-08-26 07:35
Thanks for the report. Issues fixed in:
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/2143a23a6c837e83b4c69fc5328f2b196bf47e21
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/commit/6adca00ba19047d23a229ceecfbb3fe1572fb2ab

**Closed by MrCrayfish** 2017-08-26 07:35 UTC

**Comment by njmike** [comment] 2017-08-27 13:54
Thanks!  I'm new to this - how do we make use of the fix, or has it already been included in the 4.1.2 build?

**Comment by MrCrayfish** [comment] 2017-08-27 14:56
I will be pushing a release soon!
