### ISSUE TITLE
MrCrayfishFurnitureMod 1.14.4-pre11 incompatible with Optifine

### ISSUE THREAD

**Issue by Annubis80** [MrCrayfish/MrCrayfishFurnitureMod#482] opened 2019-10-26 17:47 UTC
Is MrCrayfishFurnitureMod incompatible with the Optifine mod?  
When they are together, the Minecraft does not start with the latest version of the mod

**Comment by LorenzoPapi** [comment] 2019-10-26 17:48
Please post the client log

**Comment by Annubis80** [comment] 2019-10-26 17:55
Is the client registry the file that Launcher_log puts? 
I'm new to this sorry

**Comment by LorenzoPapi** [comment] 2019-10-26 18:06
Reopen Minecraft with the MrCrayfishFurnitureMod and optifine.
Then, go to your .minecraft folder, then go to logs folder, open "latest.log" and post it on this site: https://pastebin.com/.

**Comment by Annubis80** [comment] 2019-10-26 19:36
Hi, it's done, do I have to give you the link?

**Comment by Annubis80** [comment] 2019-10-26 19:43
https://pastebin.com/YjASLT3w

**Comment by LorenzoPapi** [comment] 2019-10-27 06:02
I can see that you have other mods. Can you tell me what happens after Minecraft starts?
Does it crash?

**Comment by Annubis80** [comment] 2019-10-27 17:47
he game freezes completely on boot and I can only close it with the task manager.
This only happens when optifine and MrCrayfishMueblesMod are together
Sorry for my english .

**Comment by LorenzoPapi** [comment] 2019-10-28 06:27
Can you send the "latest.log" after you start the game only with Optifine and MrCrayfishFurnitureMod?

**Comment by Annubis80** [comment] 2019-10-28 10:49
https://pastebin.com/Cu7GU0nz

**Comment by LorenzoPapi** [comment] 2019-10-28 15:40
I don't see anything important on the log. Can you try loading Minecraft only with Optifine and then only with MrCrayfishFurnitureMod? Now I'm going to reproduce the freeze on my pc
Edit: Try downloading and using the latest  version of Optifine and make sure you downloaded the MrCrayfishFurnitureMod from the official site(https://mrcrayfish.com/) or from curseforge.

**Comment by Annubis80** [comment] 2019-10-28 17:11
Website: https://mrcrayfish.com/   ( cfm-7.0.0-pre11-mc1.14.4)   https://pastebin.com/XYkTYPaq
Website: https://optifine.net/downloads  (OptiFine_1.14.4_HD_U_F4)   https://pastebin.com/yqCDBE5J

**Comment by LorenzoPapi** [comment] 2019-10-29 06:32
Try switching to another forge version, the latest or the recommended.

**Comment by Annubis80** [comment] 2019-10-29 08:33
I've tried with other more current versions of forge and it doesn't work

**Comment by Annubis80** [comment] 2019-10-29 08:43
I have tried other more current versions of forge and also the Recommended version 1.14.4. 28.1.0 and it doesn't work.

**Comment by Annubis80** [comment] 2019-10-29 08:46
They have a conflict between them, does the game work on your pc?

**Comment by LorenzoPapi** [comment] 2019-10-29 09:53
I've tried to start the game. But it freezes. Just as you said.
Now I'm busy, so I'll see it in a few hours.

**Comment by Annubis80** [comment] 2019-10-29 12:04
ok, thanks for helping me ;)

**Comment by nopalfi** [comment] 2019-10-29 16:02
Hello, so i have the exact problem like @Annubis80 and the exact error massage, so what i do is remove the optifine mod, and it works.
So yeah i think the mod is incompatible to optifine.
I hope it will fixed soon :)
Anyway it errors in
[Server-Worker-2/WARN] [minecraft/BlockModel]: Unable to resolve texture reference: #top in cfm:block/table_corner
When i use optifine at the same time, the error keep looping.

**Comment by Annubis80** [comment] 2019-10-29 18:02
So far I have used this version furniture-7.0.0-pre3-1.14.4 and if it works ... but when updating the mod to add new furniture I stop working ...

**Comment by LorenzoPapi** [comment] 2019-10-29 19:26
Now that I'm thinking about it, there was a big change between version. Try to update slowly.
Ex. You started from pre3. Then try downloading pre4 and start Minecraft without Optifine. If it works try with Optifine. If this works too, then update to pre5 and so on. I know it'd be boring, but that's the only method I think would work.

**Comment by WenXin20** [comment] 2019-10-29 21:51
This is interesting, I'm able to run Furniture pre11 with Optifine HD U F4 just fine if that helps any.

**Comment by Annubis80** [comment] 2019-10-29 21:54
what version of forge do you have?

**Comment by WenXin20** [comment] 2019-10-29 21:54
Forge v28.1.65

**Comment by Annubis80** [comment] 2019-10-29 21:58
I have been able to open up to the pre 10 version in the way Lorenzo mentioned, the pre11 doesn't work for me

**Comment by Annubis80** [comment] 2019-10-29 22:09
Nothing , I have left is to reinstall minecraft and try , the pre 11 does not work for me :(

**Comment by Annubis80** [comment] 2019-10-30 13:34
I have reinstalled everything and I managed to start with the pre 11 but it does not work well .

I think I give up xD, I'll play with the pre 10

**Comment by LorenzoPapi** [comment] 2019-10-30 14:05
Okay, but keep this issue open and rename it to: "MrCrayfishFurnitureMod 1.14.4-pre11 incompatible with Optifine" without quotes.

**Comment by MrCrayfish** [comment] 2019-11-16 13:02
I will be closing this issue. I have had some clarification on the issue by one of the devs of Forge (cpw). My mod is not incompatible with Optifine and I will explain.

Optifine does not adopt an async approach when loading models unlike Forge. Installing Optifine will literally double the load time because it's processing all the models on one thread rather than multiple. This has only become more apparent each update of my Furniture Mod because more blocks and models have been added. That's why pre10 loads quicker because it has less models than pre11. 

Now I'm not saying to remove Optifine. The game is actually still loading even when it's "Not Responding" so just wait and it'll eventually load. Until Optifine supports loading models asynchronously, loading time with my mod will be long.

**Closed as completed by MrCrayfish** 2019-11-16 13:02 UTC

**Comment by LorenzoPapi** [comment] 2019-11-16 13:06
Okay, MrCrayfish. Thanks for responding

**Comment by CoolScratcher** [comment] 2020-04-24 19:12
It's strange... for mine Minecraft just crashes.

**Comment by MrCrayfish** [comment] 2020-04-25 07:29
Thank you for providing no crash report, I clearly know whats wrong 🙂
