### ISSUE TITLE
[1.16.3] See through solid blocks behind a blind in open position.

### ISSUE THREAD

**Issue by NovaLynxie** [MrCrayfish/MrCrayfishFurnitureMod#625] opened 2020-10-17 15:20 UTC
**Describe the bug**
When placed on any block surface, including the mod's own blocks, the side the blinds is placed against no longer renders that side of the block's texture. I have seen a similar report #546 which has the same visual bug in their screenshots where because of this you can actually see through the world.

**Crash report**
Not a game crash, this is a visual bug.

**To Reproduce**
If applicable, the steps to reproduce the behaviour:
1. Grab or craft any wooden blinds.
2. Place down the blinds on a wall without a window or any block surface
3. Try peeking through the blind slats and you will see no block rendered behind.

**Screenshots**
![image](https://user-images.githubusercontent.com/21307676/96346351-417ed480-1093-11eb-90db-c8504afb564d.png)
![image](https://user-images.githubusercontent.com/21307676/96346505-0fba3d80-1094-11eb-8a85-91b4b2e5ef1a.png)

Please complete the following information:
- Minecraft Version: 1.16.3
- Mod Version: 7.0.0-pre19-1.16.3

**Comment by HonzaVinCZ** [comment] 2021-02-02 00:11
Same problem, same reproduce steps and same mod versions.

**Comment by NovaLynxie** [comment] 2021-02-02 15:46
Looks like this bug affects blocks which are mostly covering sides with parts exposed, not just blinds.
Similar visual bugs reported in issues #654 and #611, referencing them here in case they were overlooked.
Hopefully this gets addressed in future updates.

**Comment by MrCrayfish** [comment] 2021-06-09 21:42
Duplicate of https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/447

**Closed as completed by MrCrayfish** 2021-06-09 21:42 UTC
