### ISSUE TITLE
Optifine Conflict

### ISSUE THREAD

**Issue by Rmdhn1** [MrCrayfish/MrCrayfishFurnitureMod#508] opened 2020-01-02 10:20 UTC
Whenever i try to use version 7.0.0 pre 11 and above it crashes, just crashes, but with pre 10 and lower it works normally

**Comment by LorenzoPapi** [comment] 2020-01-02 10:30
Duplicate of https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/482.

**Comment by Rmdhn1** [comment] 2020-01-02 10:49
Hmm, there someone said they manage to get pre 11 and above working even though i reinstalled Minecraft and it still won't work, and he mentioned that it eventually will load even though it's "not responding" but for me it just crashes, i let it run and then it just crashes on it's own

**Comment by MrCrayfish** [comment] 2020-01-02 10:54
Not a bug. Optifine is not optimised. Just let the game load even if it freezes on startup. If you actually have a crash report, send it otherwise I'm not helping!

**Closed as completed by MrCrayfish** 2020-01-02 10:54 UTC

**Comment by Rmdhn1** [comment] 2020-01-02 11:05
I present you, the latest log!
https://paste.gg/p/anonymous/7dd079bacc3147bc84870b0065b797a9

**Comment by MrCrayfish** [comment] 2020-01-02 13:26
Again that is just because you are not giving the game time to launch. Actually just let it run even if it freezes or comes up with a not responding prompt. Optifine is not optimised and loads models slow.
Confirmed by Forge dev cpw: https://twitter.com/voxcpw/status/1195683361647472640
