### ISSUE TITLE
Diving board bug

### ISSUE THREAD

**Issue by Husain30** [MrCrayfish/MrCrayfishFurnitureMod#82] opened 2016-05-31 15:18 UTC

**Comment by sudo-apt-get-install** [comment] 2016-05-31 16:28
No you didn't 
Duplicate of #78

**Comment by Husain30** [comment] 2016-05-31 20:24
Oh sorry, I din't see.

**Comment by Husain30** [comment] 2016-05-31 20:26
Sorry I did not see.

**Closed** 2016-05-31 20:27 UTC
