### ISSUE TITLE
Server crash if "spam" clicking buy button in computer block

### ISSUE THREAD

**Issue by Atoru** [MrCrayfish/MrCrayfishFurnitureMod#40] opened 2016-03-11 17:45 UTC
The Pioneers modpack (Release 5)

If I try to "quickly" buy items out of the "computer" the server crashes each time I reach 16 to 24 items bought
- the server crash happens with all items that are presented in the computer..

**Comment by MrCrayfish** [comment] 2016-03-14 23:08
Crash log?

**Comment by Atoru** [comment] 2016-03-16 05:52
sorry for the wait but her it the crash log: http://pastebin.com/XSmxj46C

**Comment by MrCrayfish** [comment] 2016-03-28 10:38
Seems that Sponge handles spawning drops differently. I might be able to come up with a fix.

**Comment by Psy-Virus** [comment] 2018-11-27 21:14
There you get a crash report.
The issue is old and still exists. Just stumbled over it after a user spamed the buy button on the computer :(

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 11/27/18 10:07 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:779)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-139-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 893409064 bytes (852 MB) / 2116784128 bytes (2018 MB) up to 21206401024 bytes (20224 MB)
	JVM Flags: 9 total; -Xms512M -Xmx20G -XX:NewSize=512M -XX:MaxNewSize=1G -XX:SurvivorRatio=2 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2770 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                        | Version                  | Source                                          | Signature                                |
	|:--------- |:------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                 | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                       | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2770-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                     | 14.23.5.2770             | forge-1.12.2-14.23.5.2770-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | itemblacklist             | 1.4.0                    | ItemBlacklist-1.4.0.jar                         | None                                     |
	| UCHIJAAAA | advanced-fishing          | 1.3.2                    | Advanced-Fishing-1.12.2-1.3.2.jar               | None                                     |
	| UCHIJAAAA | antiqueatlas              | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHIJAAAA | examplemod                | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHIJAAAA | applecore                 | 3.1.4                    | AppleCore-mc1.12.2-3.1.4.jar                    | None                                     |
	| UCHIJAAAA | jei                       | 4.13.1.222               | jei_1.12.2-4.13.1.222.jar                       | None                                     |
	| UCHIJAAAA | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJAAAA | architecturecraft         | @VERSION@                | architecturecraft-1.12-3.80.jar                 | None                                     |
	| UCHIJAAAA | autoplant                 | 1.12-1.0.0               | autoplant-1.12-1.0.0.jar                        | None                                     |
	| UCHIJAAAA | backpack                  | 3.0.2                    | backpack-3.0.2-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
	| UCHIJAAAA | biomesoplenty             | 7.0.1.2411               | BiomesOPlenty-1.12.2-7.0.1.2411-universal.jar   | None                                     |
	| UCHIJAAAA | bookshelf                 | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks             | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chisel                    | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| UCHIJAAAA | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                  | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                 | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | ic2                       | 2.8.101-ex112            | industrialcraft-2-2.8.101-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | compactsolars             | 1.12.2-5.0.18.341        | CompactSolars-1.12.2-5.0.18.341-universal.jar   | None                                     |
	| UCHIJAAAA | customspawner             | 3.11.4                   | CustomMobSpawner-3.11.4.jar                     | None                                     |
	| UCHIJAAAA | customnpcs                | 1.12                     | CustomNPCs_1.12.2(26aug18).jar                  | None                                     |
	| UCHIJAAAA | mocreatures               | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar             | None                                     |
	| UCHIJAAAA | dynmap                    | 3.0-SNAPSHOT-140         | dynmap.jar                                      | None                                     |
	| UCHIJAAAA | eplus                     | 5.0.174                  | EnchantingPlus-1.12.2-5.0.174.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | enderstorage              | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | farseek                   | 2.3.1                    | Farseek-1.12-2.3.1.jar                          | None                                     |
	| UCHIJAAAA | forgemultipartcbe         | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe             | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar    | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe     | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar    | None                                     |
	| UCHIJAAAA | cfm                       | 5.17.0                   | furniture-5.17.0-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | gardenstuff               | 1.12-2.1.1               | GardenStuff-1.12-2.1.1.jar                      | None                                     |
	| UCHIJAAAA | gravestone                | 1.3.1                    | GraveStone-1.12.2-Graves-1.3.1.jar              | None                                     |
	| UCHIJAAAA | gravestone-extended       | 1.3.2                    | GraveStone-1.12.2-Extended-1.3.2.jar            | None                                     |
	| UCHIJAAAA | ichunutil                 | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | hats                      | 7.0.0                    | Hats-1.12.2-7.0.2.jar                           | None                                     |
	| UCHIJAAAA | hatstand                  | 7.0.0                    | HatStand-1.12.2-7.0.1.jar                       | None                                     |
	| UCHIJAAAA | hopperducts               | 1.5                      | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCHIJAAAA | imon_char2coal            | 1.12.2-1.02              | imon_char2coal-1.12.2-1.02.jar                  | None                                     |
	| UCHIJAAAA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | mantle                    | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                        | None                                     |
	| UCHIJAAAA | mcmultipart               | 2.5.3                    | MCMultiPart-2.5.3.jar                           | None                                     |
	| UCHIJAAAA | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar         | None                                     |
	| UCHIJAAAA | nei                       | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | harvestcraft              | 1.12.2z                  | Pam's+HarvestCraft+1.12.2za.jar                 | None                                     |
	| UCHIJAAAA | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar             | None                                     |
	| UCHIJAAAA | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar           | None                                     |
	| UCHIJAAAA | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| UCHIJAAAA | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar      | None                                     |
	| UCHIJAAAA | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar         | None                                     |
	| UCHIJAAAA | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| UCHIJAAAA | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar            | None                                     |
	| UCHIJAAAA | rangedpumps               | 0.5                      | rangedpumps-0.5.jar                             | None                                     |
	| UCHIJAAAA | ruins                     | 17.1                     | Ruins-1.12.2.jar                                | None                                     |
	| UCHIJAAAA | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
	| UCHIJAAAA | storagedrawersextra       | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar             | None                                     |
	| UCHIJAAAA | tconstruct                | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHIJAAAA | thermalfoundation         | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion          | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics           | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thutcore                  | 5.19.9                   | thutcore-1.12.2-5.19.9.jar                      | None                                     |
	| UCHIJAAAA | thutcore_compat           | 1.0                      | thutcore-1.12.2-5.19.9.jar                      | None                                     |
	| UCHIJAAAA | thuttech                  | 6.1.5                    | thuttech-1.12.2-6.1.5.jar                       | None                                     |
	| UCHIJAAAA | worldedit                 | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |
	| UCHIJAAAA | hungeroverhaul            | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar      | None                                     |

	Loaded coremods (and transformers): 
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 3 / 20; [EntityPlayerMP['AllstarBanana'/2671, l='world', x=260.40, y=69.00, z=2044.62], EntityPlayerMP['janstubbi'/2944, l='world', x=265.63, y=72.00, z=2041.11], EntityPlayerMP['PsyVirus'/3227, l='world', x=278.54, y=54.00, z=2038.32]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by MrCrayfish** [comment] 2021-06-09 16:58
Closing since I won't be maintaining 1.12.2 anymore.

**Closed by MrCrayfish** 2021-06-09 16:58 UTC
