### ISSUE TITLE
Stone variations of Furniture don't drop even when using a pickaxe

### ISSUE THREAD

**Issue by lizterr** [MrCrayfish/MrCrayfishFurnitureMod#602] opened 2020-08-03 06:27 UTC
Stone variants don't drop. Whenever you try to break it, it will not drop, even when you're using a pickaxe. Pickaxes also don't increase the mining speed on stone furniture making it a hassle to break.

**Comment by MrCrayfish** [comment] 2021-06-09 21:41
Duplicate of https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/499

**Closed as completed by MrCrayfish** 2021-06-09 21:41 UTC
